name: barev bolorin
on: 
  push:
    branches:
      - master
jobs:
  my_testing:
    runs-on: ubuntu:latest
    steps:
    - name: print hello message
      run : echo "Hello world from Testing job"
    
  my_deploy:
    runs-on: ubuntu:latest
    steps:
    - name: print hellow message
      run : echo "Helloworld from Deploy job"
